export const ROLES = {
  FOUNDER: 'founder',
  ADMIN: 'admin',
  MANAGER: 'manager',
  EMPLOYEE: 'employee'
};

export const PERMISSIONS = {
  // Contacts
  VIEW_CONTACTS: 'view_contacts',
  CREATE_CONTACT: 'create_contact',
  EDIT_CONTACT: 'edit_contact',
  DELETE_CONTACT: 'delete_contact',
  
  // Deals
  VIEW_DEALS: 'view_deals',
  CREATE_DEAL: 'create_deal',
  EDIT_DEAL: 'edit_deal',
  DELETE_DEAL: 'delete_deal',
  
  // Tasks
  VIEW_TASKS: 'view_tasks',
  CREATE_TASK: 'create_task',
  EDIT_TASK: 'edit_task',
  DELETE_TASK: 'delete_task',
  
  // Team
  VIEW_TEAM: 'view_team',
  MANAGE_TEAM: 'manage_team',
  VIEW_TEAM_STATS: 'view_team_stats',
  
  // Settings
  VIEW_SETTINGS: 'view_settings',
  EDIT_SETTINGS: 'edit_settings',
  
  // Reports
  VIEW_REPORTS: 'view_reports',
  EXPORT_REPORTS: 'export_reports',
  
  // Admin
  ADMIN_ACCESS: 'admin_access'
};

export const ROLE_PERMISSIONS = {
  [ROLES.FOUNDER]: ['*'], // Founder has all permissions
  
  [ROLES.ADMIN]: [
    PERMISSIONS.VIEW_CONTACTS,
    PERMISSIONS.CREATE_CONTACT,
    PERMISSIONS.EDIT_CONTACT,
    PERMISSIONS.DELETE_CONTACT,
    PERMISSIONS.VIEW_DEALS,
    PERMISSIONS.CREATE_DEAL,
    PERMISSIONS.EDIT_DEAL,
    PERMISSIONS.DELETE_DEAL,
    PERMISSIONS.VIEW_TASKS,
    PERMISSIONS.CREATE_TASK,
    PERMISSIONS.EDIT_TASK,
    PERMISSIONS.DELETE_TASK,
    PERMISSIONS.VIEW_TEAM,
    PERMISSIONS.MANAGE_TEAM,
    PERMISSIONS.VIEW_TEAM_STATS,
    PERMISSIONS.VIEW_SETTINGS,
    PERMISSIONS.EDIT_SETTINGS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.EXPORT_REPORTS,
    PERMISSIONS.ADMIN_ACCESS
  ],
  
  [ROLES.MANAGER]: [
    PERMISSIONS.VIEW_CONTACTS,
    PERMISSIONS.CREATE_CONTACT,
    PERMISSIONS.EDIT_CONTACT,
    PERMISSIONS.VIEW_DEALS,
    PERMISSIONS.CREATE_DEAL,
    PERMISSIONS.EDIT_DEAL,
    PERMISSIONS.VIEW_TASKS,
    PERMISSIONS.CREATE_TASK,
    PERMISSIONS.EDIT_TASK,
    PERMISSIONS.DELETE_TASK,
    PERMISSIONS.VIEW_TEAM,
    PERMISSIONS.VIEW_TEAM_STATS,
    PERMISSIONS.VIEW_REPORTS
  ],
  
  [ROLES.EMPLOYEE]: [
    PERMISSIONS.VIEW_CONTACTS,
    PERMISSIONS.CREATE_CONTACT,
    PERMISSIONS.VIEW_DEALS,
    PERMISSIONS.CREATE_DEAL,
    PERMISSIONS.VIEW_TASKS,
    PERMISSIONS.CREATE_TASK,
    PERMISSIONS.EDIT_TASK,
    PERMISSIONS.VIEW_TEAM
  ]
};